### ISSUE TITLE
Error in Django 1.8b2

### ISSUE THREAD

**Issue by v-bornov** [lukaszb/django-guardian#299]
Exception Value: 'guardian_tags' is not a valid tag library: ImportError raised loading guardian.templatetags.guardian_tags: cannot import name get_library

**Comment by wldcordeiro** [comment]
This doesn't work with Django 1.8 yet, @lukaszb hasn't pushed a new version out that addresses the backwards incompatible changes, 1.8 is on release candidate stage now too so it'd be really good to see it updated.

**Comment by lukaszb** [comment]
Yup, sorry about that. Going to review pull requests over the weekend.

**Comment by greggpb** [comment]
Any News on the pull requests to fix the django 1.8 compatability ?
